# Generated by Django 4.0.2 on 2022-02-05 18:57

from django.db import migrations
from ..models import User, UserManager


def create_super_user(apps, schema_editor):
    # ideally password should be taken from an environment variable
    User.objects.create_superuser(email="albus@hogwarts.com", password="kendra1881")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_super_user)]
