# Generated by Django 4.0.2 on 2022-02-06 22:24
from django.db import migrations
from movies.models import User, UserManager


def create_super_user(apps, schema_editor):
    # ideally password should be taken from an environment variable
    User.objects.create_superuser(
        email="albus@hogwarts.com",
        password="kendra1881",
        first_name="albus",
        last_name="dumbledore",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_super_user)]
