# Generated by Django 4.0.2 on 2022-02-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre_order_index',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
    ]
